# Generated by Django 5.1.3 on 2024-11-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('ARG', 'Argentina'), ('BR', 'Brasil'), ('CRO', 'Croacia'), ('DIN', 'Dinamarca'), ('ESP', 'Espanha'), ('FRA', 'França'), ('GEO', 'Georgia'), ('HOL', 'Holanda'), ('ITA', 'Italia'), ('JAP', 'Japao'), ('USA', 'Estados Unidos')], max_length=100, null=True),
        ),
    ]
